version: "3.8"

services:
  tictactoe-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tictactoe-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src 
      - ./checkpoints:/app/checkpoints 
      - ./frontend:/app/frontend
    working_dir: /app
    command: poetry run uvicorn tictactoe.api.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tictactoe-frontend:
    image: nginx:alpine
    container_name: tictactoe-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - tictactoe-backend
